name: Bug Report
description: Create a bug report to help us improve
body:
  - type: markdown
    attributes:
      value: |
        > ⚠️ This form is for reporting bugs only.
        > 💬 For feature requests or other types of issues, please use the appropriate template to ensure your feedback is properly addressed.
        ---
        Thank you for helping us improve Free Pet!
        To ensure we can address your report efficiently, please fill out all sections in English and provide as much detail as possible.
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen
    validations:
      required: true
  - type: markdown
    attributes:
      value: "## Environment"
  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder: ex. Ubuntu Linux 22.04
    validations:
      required: true
  - type: input
    id: free_pet_version
    attributes:
      label: Free Pet Version
      placeholder: ex. 0.1
    validations:
      required: true
