name: Feature Request
description: Suggest an idea that could improve the project
body:
  - type: markdown
    attributes:
      value: |
        > 🙌 Thanks for proposing a feature.
        > 🐞 For bugs, use the Bug Report template.
        ---
        Let's focus on the problem, your idea, and the impact.
  - type: input
    id: summary
    attributes:
      label: Summary
      placeholder: ex. Add dark mode support for the dashboard
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: What pain point or use case should this solve?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should the feature work?
    validations:
      required: true
  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: Who benefits and what improves?
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Links, mockups, or related issues
    validations:
      required: false
